inherit: 
    - models/standard.yaml
    - wandb.yaml

model:
    n_dims: 2
    n_positions: 1024

training:
    task: linear_regression   # Dont need this, change schema later
    data: gaussian # Dont need this, change schema later
    task_kwargs: {} # Dont need this, change schema later
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 200
    keep_every_steps: 200
    train_steps: 1000
    curriculum:
        dims:
            start: 2
            end: 2
            inc: 1
            interval: 2000000
        points:
            start: 2
            end: 1000
            inc: 1
            interval: 100

wandb:
    name: "test"
    entity: "afrias5"
    project: "test"




dataset_filesfolder: "./dataset_pendulum" #Folder that stores all your pickle files and logging info
pickle_folder: "picklefolder"  # Subfolder of dataset_filesfolder that will have all your pkl files
dataset_logger_textfile: "dataset_logger.txt" # Used in getData2.py for logging dataset information. Located in dataset_filesfolder


out_dir: ../models/test #Where to store model checkpoints
model_logger_textfile: "testing.txt"   #Name of txt file to save training info. Located it out_dir
test_run: False              # For debugging, this will not save checkpoints or log to wandb
use_chunk: 1                 # How you want to split dataset into chunks. 1 means load everything
loss: "mean_squared_error"   #Specify which loss to use in the tasks.py file



